server:
  port: 8080

#设置数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
#设置redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
    timeout: 0


#设置mybatis
mybatis:
  type-aliases-package: com.springboot.mapper  #设置接口包
  mapper-locations: classpath:mapperConfig/*.xml  #设置mapper文件路径

